### ISSUE TITLE
ぶらさがりユーザー一覧にアイコンがほしい

### ISSUE THREAD

**Issue by Sotalbireo** [MysticDoll/twreadedUser#2]
表題ママ。
最低限のユーザー情報っていうと

* アイコン
* ユーザーID
* スクリーンネーム

かなぁ、と。

**Comment by MysticDoll** [comment]
API側がスクレイピングなのでうまくいってない部分があるのでTwitter liteのAPIをガッとするという感じに修正する気持ちがあります

**Comment by Sotalbireo** [comment]
正直な欲を言ってしまうと、現行twitterWebの表示仕様そのままの全情報が欲しかったりする（リプライ内容やbio内容を確認しながら選択したい）んですが、そこまでやっちゃうと超軽量サービスの良さが無くなってしまうよなァと悶々としています。

**Comment by MysticDoll** [comment]
非常にわかるのでコツコツAPIのラッパを書くしかなさそうな気配がしてきました(やります)

**Comment by MysticDoll** [comment]
一応スクリーンネームクリックでそのユーザーのホームにはいけるので現状はそれで代替というつもりでいます

**Comment by MysticDoll** [comment]
#5 で対応しました
